CREATE TABLE IF NOT EXISTS users(
	id INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(150) NOT NULL,
	password VARCHAR(255) NOT NULL,
	confirmation_token VARCHAR(255),
	confirmation_token_sent_at TIMESTAMP,
	confirmed_at TIMESTAMP,
	password_reset_token VARCHAR(255),
	password_reset_token_sent_at TIMESTAMP,
	unconfirmed BOOLEAN DEFAULT TRUE NOT NULL,
	role VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(id)
);